# Company Service Deployment
apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: study-company-service
  labels:
    app: study-company-service
spec:
  selector:
    matchLabels:
      app: study-company-service
      tier: cloud-company-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: study-company-service
        tier: cloud-company-service
    spec:
      containers:
      - image: jorgelciandt/study-company-service
        name: study-company-service
        ports:
        - containerPort: 9093
          name: company
        resources:
          requests:
            cpu: 200m
            memory: 500Mi
